permalink: pretty

exclude:
  - CNAME
  - README
  - node_modules
  - package.json
  - webpack.config.js
  - webpack
  - api
  - locations
  - community-garden
  - farmers-market
  - food-pantry
  - summer-lunch
  - supermarket
  - sitemap.xml

keep_files:
  - .git
  - .gitignore
  - .nojekyll
  - CNAME
  - README
  - api
  - locations
  - community-garden
  - farmers-market
  - food-pantry
  - summer-lunch
  - supermarket
  - sitemap.xml
